services:
  - type: web
    name: chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-file=-
    envVars:
      - key: GEMINI_API_KEY
        sync: false
        value: ${GEMINI_API_KEY}